'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Shell,Heart,Code2,Sparkles,ArrowUpRight,Image,Play,Camera,X} from 'lucide-react';
type Post={id:string;caption:string;image:string;date:string};
const welcome:Post={id:'welcome',caption:'a little piece of my ocean 🐚 ยินดีต้อนรับสู่บ้านเล็ก ๆ ของมิร่า ♡',image:'/ocean.png',date:'2026-09-06'};
const social=[['Instagram','https://www.instagram.com/4rimst/'],['Twitter / X','https://x.com/4rimst'],['TikTok','https://www.tiktok.com/@4rimst'],['YouTube','https://www.youtube.com/@4rimst']];
export default function Home(){
const [tab,T]=useState('about'),[posts,P]=useState<Post[]>([welcome]),[logs,L]=useState<any[]>([]),[selected,S]=useState<Post|null>(null),[message,M]=useState(''),[key,K]=useState(''),[admin,A]=useState(false),[busy,B]=useState(false),[caption,C]=useState(''),[file,F]=useState<File|null>(null),[edit,E]=useState<string|null>(null),[likes,H]=useState<string[]>([]),[profile,Q]=useState({bio:'สวัสดีค่า มิร่าเอง ♡ ชอบทะเล อนิเมะ และการเขียนโค้ด ยินดีที่ได้รู้จักนะ!',avatar:'/ocean.png',cover:'/ocean.png'}),[bio,V]=useState('');
async function refresh(){try{const r=await fetch('/api/content');if(!r.ok)throw Error('โหลดข้อมูลไม่สำเร็จ ลองใหม่อีกครั้ง');const d:any=await r.json();P([...d.posts,welcome]);L(d.logs);if(d.profile){Q(d.profile);V(d.profile.bio);}}catch(e:any){M(e.message);}}
useEffect(()=>{refresh();const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_mira_section',description:'Open a section of Mira website',inputSchema:{type:'object',properties:{section:{type:'string',enum:['about','posts','gallery','hire','updates']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({section}:any)=>{if(!['about','posts','gallery','hire','updates'].includes(section))throw Error('Invalid section');T(section);return {section};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
async function mutate(action:string,data:any={}){B(true);try{const r=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Key':key},body:JSON.stringify({action,...data})});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(action==='login'){A(true);V(profile.bio);}else{await refresh();M('บันทึกเรียบร้อยแล้ว ♡');}return true;}catch(e:any){M(e.message);return false;}finally{B(false);}}
async function upload(f:File){if(f.size>5*1024*1024)throw Error('รูปต้องไม่เกิน 5 MB');const fd=new FormData();fd.append('file',f);const r=await fetch('/api/media',{method:'POST',headers:{'X-Admin-Key':key},body:fd});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d.url;}
async function publish(e:React.FormEvent){e.preventDefault();B(true);try{const image=file?await upload(file):posts.find(p=>p.id===edit)?.image;if(!image)throw Error('เลือกรูปภาพก่อนโพสต์นะ');if(await mutate(edit?'edit':'post',{id:edit,caption,image})){C('');F(null);E(null);}}catch(e:any){M(e.message);}finally{B(false);}}
return <><header className="topbar"><a className="brand" href="/"><Shell/>mira<span>’s little ocean</span><i>✧</i></a><div className="toplinks"><a href="https://x.com/4rimst" target="_blank" rel="noreferrer">TWITTER ↗</a><a href="https://www.instagram.com/4rimst/" target="_blank" rel="noreferrer">INSTAGRAM ↗</a><button onClick={()=>T('admin')}>♧ ADMIN</button></div></header><div className="site"><section className="hero" style={{backgroundImage:`url(${profile.cover})`}}><div className="hero-copy"><span className="eyebrow">小さな海の世界へようこそ</span><h1>somewhere,<br/>by the <em>sea.</em></h1><p>พื้นที่เล็ก ๆ ของมิร่า ที่มีเรื่องราวลอยมาตามคลื่น ♡</p><span className="hero-stamp">a little code, a little magic ✧</span></div><span className="hero-bottom">MIRA’S PERSONAL SPACE · EST. 2026</span></section><div className="below"><aside className="sidebar"><div className="profile"><div className="avatar" style={{backgroundImage:`url(${profile.avatar})`}}/><span className="online">✦</span><h2>มิร่า <span>Mira</span> <small>✿</small></h2><p className="handle">@4rimst · she / her</p><p>{profile.bio}</p><div className="facts"><span>🐚 18 years old · Thailand</span><span>♧ 15 พฤษภาคม 2008</span><span>⌘ Full stack developer</span></div><button className="primary" onClick={()=>T('hire')}>✦ มาสร้างอะไรด้วยกัน <ArrowUpRight size={16}/></button></div><section className="side-card"><h3>let’s connect <span>♡</span></h3>{social.map(([name,url],i)=><a key={name} href={url} target="_blank" rel="noreferrer"><span>{[<Image size={16}/>,<X size={16}/>,<Sparkles size={16}/>,<Play size={16}/>][i]} {name}</span><small>@4rimst ↗</small></a>)}<button onClick={async()=>{try{await navigator.clipboard.writeText('4rimst');M('คัดลอก Discord: 4rimst แล้ว ♡');}catch{M('Discord username: 4rimst');}}}><span>♧ Discord</span><small>4rimst · copy</small></button></section><section className="side-card mood"><h3>currently in my world</h3><p>🎧 ocean sounds & anime OST</p><p>💻 turning ideas into websites</p><p>🫧 collecting happy moments</p><div className="tags"><span>#anime</span><span>#oceanlover</span><span>#coding</span></div></section><p className="side-note">made of sea foam & daydreams<br/>海と夢と、ちょっとの魔法。</p></aside><main><Tabs value={tab} onValueChange={v=>T(String(v))}><TabsList className="navigation" variant="line">{[['about','♡','ABOUT ME'],['posts','▤','POSTS'],['gallery','▦','GALLERY'],['hire','⌘','จ้างงาน'],['updates','✧','UPDATES']].map(([v,icon,label])=><TabsTrigger key={v} value={v}><span>{icon}</span>{label}</TabsTrigger>)}</TabsList></Tabs><div className="content">
{tab==='about'&&<><div className="section-heading"><span>01 / A LITTLE INTRODUCTION</span><span>✦ welcome aboard</span></div><article className="card"><div className="card-title"><h2>about me <span>รู้จักกันหน่อย ♡</span></h2><Shell/></div><div className="intro"><div><span className="pill">HELLO, WORLD !</span><h3>ยินดีที่ได้รู้จัก<br/>เรียกเราว่า <em>“มิร่า”</em> ก็ได้นะ</h3><p>{profile.bio}</p><p className="english">Hi, I’m Mira — an 18-year-old full stack developer with a soft spot for anime, the ocean, and lovely little details. Welcome to my corner of the internet!</p></div><div className="portrait" style={{backgroundImage:`url(${profile.avatar})`}}><span>this is my happy place ♡</span></div></div><div className="about-bottom"><span>♡ coding with a little bit of magic</span><span>TH / EN · 日本が好き</span></div></article><div className="mini-grid"><section className="card mini"><Code2/><h3>code & create</h3><p>จากไอเดียเล็ก ๆ สู่เว็บที่ใช้งานได้จริง</p><div className="tags"><span>Frontend</span><span>Backend</span><span>Full stack</span></div></section><section className="card mini pink"><Sparkles/><h3>little things I love</h3><p>ทะเลสีฟ้า · อนิเมะ · เพลงญี่ปุ่น<br/>และวันที่ได้ทำอะไรที่ชอบ ♡</p></section></div><div className="section-heading"><span>02 / POSTCARDS FROM MY WORLD</span><button onClick={()=>T('gallery')}>view gallery ↗</button></div><div className="gallery-preview">{posts.slice(0,1).map(p=><button key={p.id} onClick={()=>S(p)}><img src={p.image} alt={p.caption}/><span>{p.caption}</span></button>)}<div className="postcard-note">a tiny ocean diary<em>เก็บความทรงจำ<br/>ไว้ตรงนี้ ♡</em><Shell size={28}/></div></div></>}
{(tab==='posts'||tab==='gallery')&&<><div className="section-heading"><span>MY LITTLE OCEAN DIARY</span><span>{posts.length} postcards ♡</span></div><h2 className="page-title">{tab==='posts'?'posts & little stories':'my gallery'} 🫧</h2><div className={tab==='gallery'?'gallery-grid':'feed'}>{posts.map(p=><article className="card post" key={p.id}><div className="post-header"><b>✿ mira <small>@4rimst</small></b><time>{p.date.slice(0,10)}</time></div><button className="post-image" onClick={()=>S(p)}><img src={p.image} alt={p.caption}/></button><div className="post-caption"><button aria-label="Like this post for this session" className={likes.includes(p.id)?'liked':''} onClick={()=>H(likes.includes(p.id)?likes.filter(x=>x!==p.id):[...likes,p.id])}><Heart size={20}/></button><p>{p.caption}</p></div></article>)}</div></>}
{tab==='hire'&&<><div className="section-heading"><span>LET’S BUILD SOMETHING LOVELY</span><span>✦ open for work</span></div><article className="card hire"><span className="pill">FULL STACK DEVELOPER</span><h2>มีไอเดียอยู่ใช่ไหม?<br/><em>มาทำให้เป็นเว็บกัน ♡</em></h2><p>รับเขียนเว็บไซต์ทั้งหน้าบ้านและหลังบ้าน<br/>Let’s turn your idea into a website that feels like you.</p><div className="price"><small>เริ่มต้น / STARTING AT</small><strong>฿2,000<span> / project</span></strong></div><div className="service-grid"><div><Code2/><h3>Frontend</h3><p>เว็บไซต์แนะนำตัว พอร์ตโฟลิโอ และหน้าเว็บที่รองรับมือถือ</p></div><div><Sparkles/><h3>Backend</h3><p>ระบบข้อมูล แอดมิน และฟังก์ชันตามขอบเขตที่ตกลงกัน</p></div></div><p className="muted">ราคาจริงขึ้นอยู่กับรายละเอียดงาน สอบถามก่อนได้เลยนะ ♡<br/>Final quote and timeline are agreed before work begins.</p><a className="primary" href="https://www.instagram.com/4rimst/" target="_blank" rel="noreferrer">คุยเรื่องงาน / Let’s talk ↗</a></article></>}
{tab==='updates'&&<><div className="section-heading"><span>THE HOUSE KEEPS GROWING</span><span>website changelog</span></div><h2 className="page-title">what’s new? ✧</h2><div className="card timeline">{[...logs,{id:'first',date:'2026-09-06',text:'เปิดบ้านเล็ก ๆ ริมทะเลของมิร่า ♡ เพิ่มหน้า About me, Gallery, จ้างงาน และระบบโพสต์'}].map(l=><div key={l.id}><time>{l.date.slice(0,10)}</time><h3>{l.text}</h3><span className="pill">WEBSITE UPDATE</span></div>)}</div></>}
{tab==='admin'&&<section className="card admin"><h2>studio <span>แอดมินของมิร่า ♡</span></h2>{!admin?<form onSubmit={e=>{e.preventDefault();mutate('login');}}><p>เข้าสู่ระบบเพื่อจัดการโพสต์และโปรไฟล์</p><label>Admin password<input type="password" required value={key} onChange={e=>K(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={busy}>เข้าสู่ระบบ / Sign in</button></form>:<><button className="text-button" onClick={()=>{A(false);K('');}}>ออกจากระบบ / Sign out</button><form onSubmit={publish}><h3>{edit?'แก้ไขโพสต์':'สร้างโพสต์ใหม่'} <Camera size={18}/></h3><label>รูปภาพ / Image (JPG, PNG, WebP · max 5 MB)<input key={edit||String(posts.length)} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>F(e.target.files?.[0]||null)}/></label><label>แคปชัน / Caption<textarea required maxLength={2000} value={caption} onChange={e=>C(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'กำลังบันทึก…':'เผยแพร่โพสต์ / Publish'}</button>{edit&&<button type="button" onClick={()=>{E(null);C('');F(null);}}>ยกเลิก</button>}</form><div className="manage-posts">{posts.filter(p=>p.id!=='welcome').map(p=><div key={p.id}><img src={p.image} alt=""/><span>{p.caption}</span><button onClick={()=>{E(p.id);C(p.caption);}}>แก้ไข</button><button disabled={busy} onClick={()=>{if(confirm('ลบโพสต์นี้? Delete this post?'))mutate('delete',{id:p.id});}}>ลบ</button></div>)}</div><form onSubmit={e=>{e.preventDefault();mutate('profile',{...profile,bio});}}><h3>โปรไฟล์ / Profile</h3><label>ข้อความแนะนำตัว<textarea required maxLength={1000} value={bio} onChange={e=>V(e.target.value)}/></label>{['avatar','cover'].map(k=><label key={k}>{k==='avatar'?'รูปโปรไฟล์':'ภาพปก'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;B(true);try{const url=await upload(f);await mutate('profile',{...profile,bio,[k]:url});}catch(e:any){M(e.message);}finally{B(false);}}}/></label>)}<button className="primary" disabled={busy}>บันทึกโปรไฟล์</button></form><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const text=new FormData(form).get('update');if(await mutate('log',{text}))form.reset();}}><h3>เพิ่มบันทึกอัปเดต</h3><label>มีอะไรเปลี่ยนแปลงบ้าง?<textarea name="update" required maxLength={1000}/></label><button className="primary" disabled={busy}>บันทึกอัปเดต</button></form></>}</section>}
</div><footer>crafted with ♡ & a little ocean magic <span>© 2026 MIRA · @4rimst</span></footer></main></div></div>{message&&<div role="status" className="toast">{message}<button aria-label="Dismiss" onClick={()=>M('')}><X size={16}/></button></div>}<Dialog open={!!selected} onOpenChange={open=>{if(!open)S(null);}}><DialogContent className="lightbox"><DialogTitle>{selected?.caption||'Postcard'}</DialogTitle>{selected&&<><img src={selected.image} alt={selected.caption}/><p>{selected.date.slice(0,10)} · @4rimst</p></>}</DialogContent></Dialog></>;
}


